apiVersion: v1
kind: Service
metadata:
  name: expense-service
  namespace: expense-prod
spec:
  selector:
    app: expense-tracker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer